// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oquvpausnnqjunwpmger.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdXZwYXVzbm5xanVud3BtZ2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzODYxOTUsImV4cCI6MjA2Nzk2MjE5NX0.rAhTWvi2SLHZ9zqSyQzVwN573r5I-7yQXkBlfwUrAAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});